Repository lambdalabs-eu1-webchat/webchat-backend, pull requests merged in 2019-04, with the labels that each got.

#4 Create basic express app
  .gitignore
  api/consts/error.js
  api/consts/response.js
  api/consts/url.js
  api/server.js
  api/users/userHandlers.js
  api/users/userRoutes.js
  dummyData.js/users.js
  index.js
  package.json
  yarn.lock
Labels: new-feature

#5 Users model
  .gitignore
  api/server.js
  api/users/userRoutes.js
  data/seedUsers.js
  index.js
  models/index.js
  models/usersModel.js
  package.json
  yarn.lock
Labels: new-feature

#6 Backend config changes
  .eslintrc.json
  api/consts/error.js
  api/consts/url.js
  api/server.js
  api/users/userHandlers.js
  api/users/userRoutes.js
  data/seedUsers.js
  dummyData.js/users.js
  index.js
  models/index.js
  package.json
  pull_request_template.md
  routes/userRoutes.js
  schemas/index.js
  schemas/usersSchema.js
  utils/error.js
  utils/response.js
  utils/url.js
  yarn.lock
Labels: new-feature

#8 Backend logger
  .eslintrc.json
  api/server.js
  data/seedUsers.js
  index.js
  middleware/index.js
  middleware/winston.js
  models/index.js
  models/usersSchema.js
  package.json
  routes/index.js
  routes/userRoutes.js
  utils/path.js
  utils/url.js
  yarn.lock
Labels: breaking-change, new-feature

#21 Models
  .eslintrc.json
  api/server.js
  data/index.js
  data/seedChats.js
  data/seedHotels.js
  data/seedUsers.js
  index.js
  middleware/winston.js
  models/MODEL_NAMES.js
  models/chatsModels.js
  models/hotelModels.js
  models/index.js
  models/usersSchema.js
  routes/index.js
Labels: breaking-change, new-feature

#22 User endpoints
  .gitignore
  api/server.js
  index.js
  models/usersModel.js
  package.json
  routes/userRoutes.js
  utils/error.js
  utils/response.js
  yarn.lock
Labels: breaking-change, new-feature

#23 Hotel model endpoints
  middleware/formatHotel.js
  middleware/validateHotelChange.js
  middleware/validateHotelPost.js
  middleware/validateObjectId.js
  models/index.js
  models/usersModels.js
  routes/hotelRoutes.js
  routes/index.js
  routes/userRoutes.js
  utils/documentExists.js
  utils/error.js
  utils/errorMessage.js
  utils/path.js
Labels: breaking-change, new-feature

#24 Authentication
  .eslintignore
  api/server.js
  data/seedChats.js
  data/seedHotels.js
  data/seedUsers.js
  index.js
  middleware/auth.js
  models/MODEL_NAMES.js
  models/chatsModels.js
  models/hotelModels.js
  models/index.js
  package.json
  routes/auth.js
  routes/index.js
  routes/userRoutes.js
  tests/integration/auth.test.js
  utils/createToken.js
  utils/errorMessage.js
  utils/path.js
  utils/secrets.js
  yarn.lock
Labels: breaking-change, new-feature

#26 Scale seeds
  .gitignore
  apidoc.json
  data/index.js
  data/seedChats.js
  data/seedHotels.js
  data/seedUsers.js
  index.js
  models/TICKET_STATUSES.js
  models/USER_TYPES.js
  models/chatsModels.js
  models/hotelModels.js
  package.json
  utils/helperFunctions.js
  yarn.lock
Labels: bug-fix, new-feature

#28 Setup apidocs
  routes/endpoint-docs/authDocs.js
  routes/endpoint-docs/hotelRoutesDocs.js
  routes/endpoint-docs/userRoutes.js
  routes/hotelRoutes.js
Labels: documentation

#30 Auth testing
  jest.config.js
  package.json
  tests/integration/auth.test.js
Labels: new-feature
