Repository lambdalabs-eu1-webchat/webchat-backend, pull requests merged in 2019-05, with the labels that each got.

#29 Updated documentation for user endpoints
  routes/endpoint-docs/userRoutes.js
  routes/userRoutes.js
  utils/errorMessage.js
Labels: bug-fix, documentation

#31 Testing models and Re-added Validation
  jest.config.js
  models/chatsModels.js
  models/hotelModels.js
  models/usersModels.js
  tests/integration/auth.test.js
  tests/mongoose/chats.test.js
  tests/mongoose/hotels.test.js
  tests/mongoose/users.test.js
Labels: new-feature

#32 Room endpoints
  middleware/validateHotelChange.js
  middleware/validateRoomChange.js
  middleware/validateRoomsArr.js
  middleware/validateSubDocObjectId.js
  routes/hotelRoutes.js
  routes/index.js
  routes/roomRoutes.js
  utils/capitalizeLetters.js
  utils/errorMessage.js
  utils/response.js
  utils/subDocumentExists.js
Labels: new-feature

#36 Users testing
  routes/userRoutes.js
  tests/integration/users.test.js
Labels: testing

#38 Hotel endpoints testing
  tests/integration/auth.test.js
  tests/integration/hotel.test.js
  tests/integration/users.test.js
Labels: breaking-change, testing

#40 Room endpoints testing
  tests/integration/hotel.test.js
  tests/integration/rooms.test.js
Labels: testing

#41 Put request checks
  data/seedChats.js
  data/seedUsers.js
  models/chatsModels.js
  models/hotelModels.js
  models/usersModels.js
  package.json
  routes/endpoint-docs/userRoutesDocs.js
  routes/hotelRoutes.js
  routes/index.js
  routes/userRoutes.js
  tests/integration/auth.test.js
  tests/integration/hotel.test.js
  tests/integration/rooms.test.js
  tests/integration/users.test.js
  tests/mongoose/chats.test.js
  tests/mongoose/users.test.js
  utils/MODEL_NAMES.js
  utils/TICKET_STATUSES.js
  utils/USER_TYPES.js
  utils/errorMessage.js
  utils/helperFunctions.js
Labels: new-feature, testing

#43 Api rooms doc
  routes/endpoint-docs/roomRoutesDocs.js
  routes/endpoint-docs/userRoutesDocs.js
Labels: documentation

#45 Messaging Socket
  api/server.js
  index.js
  package.json
  routes/auth.js
  routes/chats/assignSelfTicket.js
  routes/chats/closeTicketFunction.js
  routes/chats/constants.js
  routes/chats/index.js
  routes/chats/joinFunction.js
  routes/chats/messageFunction.js
  routes/endpoint-docs/chatsDocs.js
  utils/createToken.js
  utils/getLastTicket.js
  utils/isUserType.js
Labels: documentation, new-feature, work-in-progress

#47 Payment routes stripe integration
  package.json
  routes/index.js
  routes/paymentRoutes.js
  utils/PAYMENT_PLANS.js
  utils/errorMessage.js
  utils/path.js
Labels: new-feature, work-in-progress

#44 Chat code
  models/index.js
  models/usersModels.js
  routes/auth.js
  routes/chatAuth.js
  routes/index.js
  routes/userRoutes.js
  tests/integration/users.test.js
  utils/createPassCode.js
  utils/createToken.js
  utils/errorMessage.js
  utils/response.js
Labels: breaking-change, new-feature

#49 updated schema for stripe
  models/hotelModels.js
  routes/chats/index.js
  utils/PAYMENT_PLANS.js
Labels: new-feature

#52 Separated GET users by hotel id from GET user by id
  routes/userRoutes.js
  tests/integration/auth.test.js
  tests/integration/users.test.js
Labels: bug-fix

#50 return passcode when making a guest
  routes/chatAuth.js
  routes/userRoutes.js
Labels: bug-fix

#56 Create hotel on Super Admin registration
  middleware/validateHotelPost.js
  models/usersModels.js
  routes/auth.js
  routes/endpoint-docs/authDocs.js
  routes/hotelRoutes.js
  routes/userRoutes.js
  tests/integration/auth.test.js
  tests/integration/hotel.test.js
  tests/integration/rooms.test.js
  utils/errorMessage.js
Labels: documentation, new-feature

#60 Hotels rooms docs update
  routes/endpoint-docs/hotelRoutesDocs.js
  routes/endpoint-docs/roomRoutesDocs.js
Labels: documentation

#57 Chats rating
  routes/chats/closeTicketFunction.js
  routes/chats/index.js
  routes/chats/ratingFunction.js
  routes/endpoint-docs/chatsDocs.js
Labels: bug-fix, new-feature

#59 Payment routes db integration
  package.json
  routes/endpoint-docs/paymentRoutesDocs.js
  routes/paymentRoutes.js
  utils/PAYMENT_PLANS.js
  utils/checkPlanLegibility.js
  utils/errorMessage.js
  utils/url.js
Labels: new-feature

#61 fixed small typos
  routes/chats/closeTicketFunction.js
  routes/chats/constants.js
  routes/chats/index.js
  routes/chats/joinFunction.js
Labels: bug-fix

#63 Chats routes
  routes/chatsRoutes.js
  routes/index.js
  utils/errorMessage.js
  utils/path.js
Labels: new-feature

#64 Added fixes
  routes/paymentRoutes.js
Labels: bug-fix

#66 added get hotel guests
  routes/hotelRoutes.js
Labels: new-feature

#65 fixed a bug thatcaused by disconnect crashing server
  routes/chats/index.js
Labels: bug-fix

#67 done get available rooms route
  routes/hotelRoutes.js
  routes/roomRoutes.js
  utils/errorMessage.js
Labels: new-feature

#69 fixed bug of Emitting chats to wrong place
  routes/chats/assignSelfTicket.js
Labels: bug-fix

#70 Ticket chats
  routes/chats/constants.js
  routes/chats/messageFunction.js
Labels: bug-fix

#71 User typing
  routes/chatAuth.js
  routes/chats/constants.js
  routes/chats/index.js
  routes/chats/typingFunction.js
Labels: bug-fix, new-feature

#73 Qr generator
  routes/userRoutes.js
  utils/createPassCode.js
  utils/createToken.js
Labels: bug-fix

#74 fixed bug of not changing ticket status to active on join
  routes/chats/assignSelfTicket.js
Labels: bug-fix

#76 Email routes
  package.json
  routes/chatsRoutes.js
  routes/emailRoutes.js
  routes/index.js
  utils/createEmail.js
  utils/email.js
  utils/errorMessage.js
  utils/formatChatOnCheckout.js
  utils/getChatOnCheckout.js
  utils/getGuest.js
  utils/getHotel.js
  utils/path.js
  utils/response.js
  utils/validateEmail.js
Labels: new-feature

#80 Chat bugs for guest client
  routes/chats/constants.js
  routes/chats/index.js
  routes/chats/updateGuestChat.js
Labels: bug-fix

#79 Update chat/email endpoint docs
  routes/endpoint-docs/chatsRoutesDocs.js
  routes/endpoint-docs/emailRoutesDocs.js
  utils/errorMessage.js
Labels: documentation

#83 Translate api
  api/translate.js
  models/chatsModels.js
  package.json
  routes/chatsRoutes.js
Labels: new-feature

#85 Socket logout
  routes/chats/constants.js
  routes/chats/index.js
Labels: bug-fix

#87 Translate api production
  api/translate.js
  package.json
  routes/chatsRoutes.js
Labels: bug-fix

#88 Save text to translate in array
  api/translate.js
Labels: bug-fix

#91 Small fixes
  api/translate.js
  routes/userRoutes.js
  utils/checkPlanLegibility.js
Labels: bug-fix

#92 db coverts to lower case and login and guest login uses lower case
  models/usersModels.js
  routes/auth.js
  routes/chatAuth.js
Labels: breaking-change, bug-fix

#93 Checkout close chats
  routes/chats/checkout.js
  routes/chats/constants.js
  routes/chats/index.js
  routes/userRoutes.js
Labels: bug-fix

#97 Added document exists check and associated server response for email …
  routes/userRoutes.js
Labels: bug-fix

#98 Fixed merge
  routes/userRoutes.js
Labels: bug-fix

#100 Fixed bug for creating guest users
  routes/userRoutes.js
Labels: bug-fix

#101 Back end - Restricted routes
  config/restricted.js
  index.js
  middleware/auth.js
  package.json
  routes/auth.js
  routes/chatAuth.js
  routes/chatsRoutes.js
  routes/emailRoutes.js
  routes/hotelRoutes.js
  routes/paymentRoutes.js
  routes/roomRoutes.js
  routes/userRoutes.js
  utils/checkPlanLegibility.js
  utils/createToken.js
  utils/getChatOnCheckout.js
  utils/getGuest.js
  utils/getHotel.js
Labels: breaking-change

#103 Added doc check for duplicate email
  routes/userRoutes.js
Labels: bug-fix

#105 Remove guest name from passcode generator
  routes/userRoutes.js
  utils/createPassCode.js
Labels: bug-fix

#106 Edit access
  routes/userRoutes.js
  utils/errorMessage.js
  utils/isUserTypeAllowedChange.js
Labels: bug-fix
